<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Services, new_f1i5a5z atm_c8_2n3zc atm__893637</name>
   <tag></tag>
   <elementGuidId>540852eb-9cb3-46b3-94df-3d220ca3e6e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.f1i5a5z.atm_c8_2n3zc.atm_g3_12um922.atm_fr_rpsos.atm_cs_10d11i2.atm_7l_dezgoh.atm_le_yh40bf.atm_vv_1q9ccgz.atm_ks_zryt35.atm_sq_1l2sidv.dir.dir-ltr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Services, new'])[1]/following::div[10]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Where&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bb2558cc-628b-4525-8075-d29f6e6fec5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>f1i5a5z atm_c8_2n3zc atm_g3_12um922 atm_fr_rpsos atm_cs_10d11i2 atm_7l_dezgoh atm_le_yh40bf atm_vv_1q9ccgz atm_ks_zryt35 atm_sq_1l2sidv dir dir-ltr</value>
      <webElementGuid>3524d53a-caaf-4ead-a48a-0ca94ad0586c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Where</value>
      <webElementGuid>6cd041b2-51ae-48d5-980b-3b465cd4ab3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-application&quot;)/div[1]/div[@class=&quot;t1bgcr6e  cjz5kiq&quot;]/div[1]/div[1]/div[@class=&quot;r9m3m4o atm_eohtre_1wfwpv5 atm_1gwwzir_u29brm atm_eohtre_mm87nz__jx8car atm_1gwwzir_rw9lz9__jx8car dir dir-ltr&quot;]/div[1]/div[@class=&quot;m1wgxt7p atm_lcucu6_exct8b atm_ys9she_69rp3d__jx8car atm_ys9she_12mkxmp__1z0u2lb atm_lcucu6_1tcgj5g__kgj4qw atm_lcucu6_1tcgj5g__oggzyc atm_lcucu6_1vi7ecw__1v156lz atm_lcucu6_1vi7ecw__qky54b atm_lcucu6_fyhuej__jx8car dir dir-ltr&quot;]/div[@class=&quot;w1hvh9qj atm_mk_1if85x1 atm_tk_idpfg4 atm_vy_1osqo2v atm_wq_b4wlg atm_h3_1wmurcz dir dir-ltr&quot;]/div[@class=&quot;c1yo0219 atm_9s_1txwivl_vmtskl atm_92_1yyfdc7_vmtskl atm_9s_1txwivl_9in345 atm_92_1yyfdc7_9in345 dir dir-ltr&quot;]/div[1]/header[@class=&quot;c1ftp51f atm_9s_1txwivl atm_fc_1yb4nlp atm_h_1h6ojuz atm_gi_xjk4d9 atm_j3_1vvhni0 atm_lk_1ph3nq8 atm_ll_1ph3nq8 atm_e2_u29brm atm_lk_n9wab5__1v156lz atm_ll_n9wab5__1v156lz atm_lk_dnsvzo__jx8car atm_ll_dnsvzo__jx8car atm_e2_rw9lz9__jx8car dir dir-ltr&quot;]/form[@class=&quot;f1hztvqy atm_vy_1osqo2v atm_e2_1osqo2v atm_mk_stnw88 atm_tk_idpfg4 atm_fq_idpfg4 atm_lh_ke7zzc atm_wq_idpfg4 dir dir-ltr&quot;]/div[@class=&quot;csjaj27 atm_vy_1osqo2v atm_9s_1txwivl atm_h_1h6ojuz atm_ar_1bp4okc atm_mk_h2mmj6 atm_wq_kb7nvz atm_h3_ftgil2__jx8car dir dir-ltr&quot;]/div[1]/div[@class=&quot;cwxaa06 atm_mk_stnw88 atm_fq_1ssbidh atm_tr_zr6sja atm_j3_1v7idld atm_vy_1osqo2v atm_e2_1k4yqc2 atm_9s_1txwivl atm_5j_1vi7ecw atm_cx_1fwxnve atm_fc_1yb4nlp atm_h_1h6ojuz dir dir-ltr&quot;]/div[@class=&quot;fam02bu atm_9s_11p5wf0 atm_vy_1osqo2v atm_e2_1osqo2v atm_26_1j28jx2 atm_h_1h6ojuz atm_cx_yh40bf atm_5j_1vi7ecw fwvguhx atm_dz_1pfszjl dir dir-ltr&quot;]/div[@class=&quot;f1xmefpa atm_mk_h2mmj6 atm_9j_tlke0l atm_5j_1vi7ecw atm_e2_1osqo2v atm_vy_1osqo2v atm_9s_1txwivl atm_h_1h6ojuz atm_fc_1yb4nlp atm_kd_glywfm atm_70_hsdql2_1w3cfyq atm_92_1yyfdc7_vmtskl atm_mk_stnw88_vmtskl atm_tk_1ssbidh_vmtskl atm_tr_1i34xl8_vmtskl atm_fq_myb0kj_vmtskl atm_vy_54a6mi_vmtskl atm_e2_1vi7ecw_vmtskl atm_2d_1j28jx2_vmtskl atm_wq_1mrwo0b_vmtskl atm_mj_glywfm_vmtskl atm_92_1yyfdc7_9in345 atm_mk_stnw88_9in345 atm_tk_idpfg4_9in345 atm_vy_u0ciey_9in345 atm_e2_1osqo2v_9in345 atm_26_1j28jx2_9in345 atm_5j_1vi7ecw_9in345 atm_wq_1mrwo0b_9in345 atm_mj_glywfm_9in345 f1juqfxu f1nybgd7 atm_26_1oqmvsg_1nos8r atm_2d_1s7alg2_1rqz0hn fjdyumq atm_vy_1pbc45q_1rqz0hn atm_fq_1y44olf_1rqz0hn atm_fq_idpfg4_1g7d7jc f67r5k6 atm_k4_idpfg4_1rqz0hn dir dir-ltr&quot;]/div[@class=&quot;f1o8nkkf atm_mk_h2mmj6 atm_wq_cs5v99 atm_vy_1osqo2v atm_jb_idpfg4 atm_ks_zryt35 f8h9euk atm_l8_115qw9y dir dir-ltr&quot;]/div[@class=&quot;f1i5a5z atm_c8_2n3zc atm_g3_12um922 atm_fr_rpsos atm_cs_10d11i2 atm_7l_dezgoh atm_le_yh40bf atm_vv_1q9ccgz atm_ks_zryt35 atm_sq_1l2sidv dir dir-ltr&quot;]</value>
      <webElementGuid>89a4a6c2-6eaf-4682-9991-2684976a95f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-application']/div/div/div/div/div/div/div[2]/div/div/div/header/form/div/div/div[2]/div[2]/div/div[2]/div</value>
      <webElementGuid>1b5852ef-365c-4b6d-b33b-10d173bce49b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Services, new'])[1]/following::div[10]</value>
      <webElementGuid>ab21e61c-a9ef-4ab7-9a16-b57085ec24d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check in'])[1]/preceding::div[3]</value>
      <webElementGuid>99a95d7f-6df4-4ef8-a5b3-295c85fc4560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add dates'])[1]/preceding::div[4]</value>
      <webElementGuid>57eee088-a8df-4c88-a411-533cd32cb1e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Where']/parent::*</value>
      <webElementGuid>29cd32a5-f39c-4879-8000-09d1fe8f02d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div</value>
      <webElementGuid>49005304-4433-4c62-b9bc-9fbec45bae96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Where' or . = 'Where')]</value>
      <webElementGuid>9f70bd9d-a81b-410e-ad7c-aeaa8b16269f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
